import pandas as pd

TOTAL_PERMS = 500
RESOURCES = '../resources'

def collect_sequences(base_dir):
    seqs = []
    def recursive_search(path):
        if path.is_dir():
            for each_path in path.iterdir():
                recursive_search(each_path)
        else:
            if path.suffix == '.fa':
                seqs.append(path)
    
    recursive_search(base_dir)

    return seqs

sequence_dir = Path(RESOURCES).joinpath('sequences')
sequences = collect_sequences(sequence_dir)
sequence_names = [p.stem for p in sequences]

# Create sequence name to path dictionary so snakemake rules can lookup paths easily
seq_paths = {p.stem: p for p in sequences}


include: 'rules/dr_t.smk'
include: 'rules/process_drt.smk'


rule all:
    input:
        expand(
            'output/DrTransformer/{plasmid}/perm-{perm_num}',
            plasmid=sequence_names, perm_num=range(TOTAL_PERMS)
        ),
        expand(
            'output/DrTransformerOGSeqs/{plasmid}/',
            plasmid=sequence_names, perm_num=range(TOTAL_PERMS)
        )